In [2]:
import numpy as np


In [4]:
x=np.array([[0,0],[0,1],[1,0],[1,1]])
x

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [5]:
y=[0,1,1,1]
y

[0, 1, 1, 1]

In [6]:
w=np.array([1,1])
w

array([1, 1])

In [9]:
b =-0.5 # b => bais hai

In [13]:
def activation(y_hat):
    if y_hat >=0:
        return 1
    else:
        return 0

In [17]:
pred=[]
for a in x:
    y_hat=np.dot(a,w)+b
    pred.append(activation(y_hat))
    # pred.append(y_hat)
    

In [19]:
pred

[-0.5, 0.5, 0.5, 1.5]

In [1]:
import numpy as np
import math

In [2]:
epochs=100
alpha=0.2

In [18]:
w0=np.random.random()
w1=np.random.random()
w2=np.random.random()
print("Initial Weights")
print("w0= ",w0,"w1= ",w1,"w2=  ",w2)

Initial Weights
w0=  0.4051252990442302 w1=  0.8757443249679738 w2=   0.5525440285903082


In [6]:
del_w0=1
del_w1=1
del_w2=1

In [8]:
train_data_temp=[[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]]
train_data=np.asarray(train_data_temp)
op=np.array([0,1,1,1,1,1,1,1])

In [9]:
train_data

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]])

In [10]:
op

array([0, 1, 1, 1, 1, 1, 1, 1])

In [13]:
bias=0

In [17]:

for i in range(epochs):
    j=0
    for x in train_data:
        y_hat=w0*x[0]+w1*x[1]+w2*x[2]+bias
    
        if y_hat >=0:
            act=1
        else:
            act=0
    
        error=op[j]-act
    
        del_w0=alpha*x[0]*error
        del_w1=alpha*x[1]*error
        del_w2=alpha*x[2]*error
    
        w0=w0+del_w0
        w1=w1+del_w1
        w2=w2+del_w2

        j=j+1
        print("epoch",i+1,"error",error)
        print(del_w0,del_w1,del_w2)

print("\nFinal weight = ")
print("w0 = ",w0,"w1 = ",w1,"w2 = ",w2)
    
     

epoch 1 error -1
-0.0 -0.0 -0.0
epoch 1 error 0
0.0 0.0 0.0
epoch 1 error 0
0.0 0.0 0.0
epoch 1 error 0
0.0 0.0 0.0
epoch 1 error 0
0.0 0.0 0.0
epoch 1 error 0
0.0 0.0 0.0
epoch 1 error 0
0.0 0.0 0.0
epoch 1 error 0
0.0 0.0 0.0
epoch 2 error -1
-0.0 -0.0 -0.0
epoch 2 error 0
0.0 0.0 0.0
epoch 2 error 0
0.0 0.0 0.0
epoch 2 error 0
0.0 0.0 0.0
epoch 2 error 0
0.0 0.0 0.0
epoch 2 error 0
0.0 0.0 0.0
epoch 2 error 0
0.0 0.0 0.0
epoch 2 error 0
0.0 0.0 0.0
epoch 3 error -1
-0.0 -0.0 -0.0
epoch 3 error 0
0.0 0.0 0.0
epoch 3 error 0
0.0 0.0 0.0
epoch 3 error 0
0.0 0.0 0.0
epoch 3 error 0
0.0 0.0 0.0
epoch 3 error 0
0.0 0.0 0.0
epoch 3 error 0
0.0 0.0 0.0
epoch 3 error 0
0.0 0.0 0.0
epoch 4 error -1
-0.0 -0.0 -0.0
epoch 4 error 0
0.0 0.0 0.0
epoch 4 error 0
0.0 0.0 0.0
epoch 4 error 0
0.0 0.0 0.0
epoch 4 error 0
0.0 0.0 0.0
epoch 4 error 0
0.0 0.0 0.0
epoch 4 error 0
0.0 0.0 0.0
epoch 4 error 0
0.0 0.0 0.0
epoch 5 error -1
-0.0 -0.0 -0.0
epoch 5 error 0
0.0 0.0 0.0
epoch 5 error 0
0.0 0.0 0.0
