In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, roc_curve, auc
from sklearn.datasets import make_classification 

import warnings
warnings.filterwarnings('ignore')

In [6]:
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=2)

In [27]:
# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)


In [28]:
model = LogisticRegression()


In [29]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
param = {'penalty':('l1','l2', 'elasticnet'), 'C':[1, 2, 10, 30, 40]}
clf = GridSearchCV(model,param_grid=param, cv=5)

In [30]:
clf.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 10, 30, 40],
                         'penalty': ('l1', 'l2', 'elasticnet')})

In [31]:
clf.best_params_

{'C': 1, 'penalty': 'l2'}

In [32]:
y_pred_clf = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred_clf))
print(classification_report(y_test, y_pred_clf))
print(accuracy_score(y_test, y_pred_clf))

[[112  31]
 [ 62  95]]
              precision    recall  f1-score   support

           0       0.64      0.78      0.71       143
           1       0.75      0.61      0.67       157

    accuracy                           0.69       300
   macro avg       0.70      0.69      0.69       300
weighted avg       0.70      0.69      0.69       300

0.69


In [33]:
model = LogisticRegression(penalty='l2',C=1)

In [34]:
model

LogisticRegression(C=1)

In [35]:
model.fit(X_train,y_train)

LogisticRegression(C=1)

In [36]:
y_pred = model.predict(X_test)

In [37]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[112  31]
 [ 62  95]]
              precision    recall  f1-score   support

           0       0.64      0.78      0.71       143
           1       0.75      0.61      0.67       157

    accuracy                           0.69       300
   macro avg       0.70      0.69      0.69       300
weighted avg       0.70      0.69      0.69       300

0.69


In [40]:
# Random Search Cross Vailidation
randomozer_clf = RandomizedSearchCV(model, param_distributions=param, cv=5, n_iter=10)

In [41]:
randomozer_clf.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(C=1),
                   param_distributions={'C': [1, 2, 10, 30, 40],
                                        'penalty': ('l1', 'l2', 'elasticnet')})

In [42]:
randomozer_clf.best_params_

{'penalty': 'l2', 'C': 10}

In [43]:
model = LogisticRegression(penalty='l2',C=10)
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[112  31]
 [ 62  95]]
              precision    recall  f1-score   support

           0       0.64      0.78      0.71       143
           1       0.75      0.61      0.67       157

    accuracy                           0.69       300
   macro avg       0.70      0.69      0.69       300
weighted avg       0.70      0.69      0.69       300

0.69
